version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # Hot-reload for FastAPI

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app        # Hot-reload for React
      - /app/node_modules      # Avoid overwriting node_modules
    depends_on:
      - backend